### PR TITLE
Update to use zig package manager

### LINKED ISSUE #14: Update to support official Zig package manager
The Zig package manager [has landed](https://github.com/ziglang/zig/pull/14265). 

It doesn't look like git submodules are supported, so the build would need to add the raylib source repository as a package dependency instead. There would be a few minor updates required for `build.zig` to register the zig module (and maybe the raylib artifact).

### PR DESCRIPTION
**Pull request by deevus**
Changes:
- Removed `raylib` submodule
- Added `build.zig.zon` with raylib as dependency

Todo:
- [x] Update JSON calls in `generate.zig`
- [ ] Update or remove `addTo` function
- [ ] Test adding as a dependency to a project

Fixes #14

### CODE REVIEW

**Comment by ryupold** [comment]
I haven't read into the documentation of the package manager yet. 
Not sure if I manage to find time this week to look into it.
Probably next week.
At least I fixed the JSON parsing calls today.
Thanks for the preliminary work setting up the build.zig.zon

**Comment by deevus** [comment]
No problem. 

> I haven't read into the documentation of the package manager yet.

What documenation? 😅 I had a poke through the source code in addition to reading over @andrewrk's test repo here: https://github.com/andrewrk/ffmpeg

**Comment by gabstv** [comment]
Will this PR be reconsidered since the package manager is now supported in the latest stable release (0.11.x)?

**Comment by deevus** [comment]
Closing in favour of #38

**Pull request closed without merging**
